# Generated by Django 3.2.13 on 2022-07-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_times',
            name='time_diff',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
