# Generated by Django 3.2.13 on 2022-07-13 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_staff_times_time_diff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_times',
            name='time_diff',
        ),
    ]
