# Generated by Django 3.2.13 on 2022-07-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_remove_staff_times_time_diff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_times',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='staff_times',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
