# Generated by Django 3.2.13 on 2022-07-13 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_auto_20220713_2116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff_times',
        ),
    ]
