# Generated by Django 3.2.13 on 2022-07-14 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_staff_times'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff_times',
        ),
    ]
