# Generated by Django 3.2.4 on 2022-01-26 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_rename_date_time_customer_created_date'),
        ('Jobs', '0002_alter_make_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acessories', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Fault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Job_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_status', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Sale_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_item', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='model',
            name='imei',
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('imei', models.CharField(max_length=250)),
                ('passcode', models.CharField(max_length=250)),
                ('cost', models.IntegerField()),
                ('collection_time', models.DateField()),
                ('payment_status', models.CharField(choices=[('PAID', 'PAID'), ('UNPAID', 'UNPAID'), ('CREDIT NOTE', 'CREDIT NOTE')], max_length=250)),
                ('acessories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_acessories', to='Jobs.accessories')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_customer', to='customer.customer')),
                ('fault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_faults', to='Jobs.fault')),
                ('job_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_job_status', to='Jobs.job_status')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_make', to='Jobs.make')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_model', to='Jobs.model')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_network', to='Jobs.network')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_acessories', to='Jobs.sale_item')),
            ],
        ),
    ]
