# Generated by Django 3.2.4 on 2022-01-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0004_jobs_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='collection_time',
            field=models.DateTimeField(),
        ),
    ]
