# Generated by Django 3.2.4 on 2022-01-27 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0005_alter_jobs_collection_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessories',
            old_name='acessories',
            new_name='accessories',
        ),
    ]
