# Generated by Django 3.2.4 on 2022-01-28 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0007_alter_jobs_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='acessories',
            new_name='accessories',
        ),
    ]
