# Generated by Django 3.2.4 on 2022-01-28 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0009_jobs_job_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='job_id',
        ),
    ]
