# Generated by Django 3.2.4 on 2022-02-12 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0014_fingerprints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fingerprints',
            old_name='date_time',
            new_name='date_time_fprint',
        ),
        migrations.RenameField(
            model_name='fingerprints',
            old_name='user',
            new_name='user_fprint',
        ),
        migrations.AddField(
            model_name='fingerprints',
            name='job_fprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Jobs.jobs'),
        ),
    ]
