# Generated by Django 3.2.4 on 2022-02-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0015_auto_20220212_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprints',
            name='date_time_fprint',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
