# Generated by Django 3.2.4 on 2022-02-13 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0016_alter_fingerprints_date_time_fprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reciepts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Jobs.jobs')),
            ],
        ),
    ]
