# Generated by Django 3.2.4 on 2022-02-16 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0018_contact_by_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complete_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_job', models.TextField(blank=True, null=True)),
                ('c_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Jobs.jobs')),
            ],
        ),
    ]
