# Generated by Django 3.2.4 on 2022-02-17 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0019_complete_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_by_email',
        ),
    ]
