# Generated by Django 3.2.4 on 2022-02-18 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0020_delete_contact_by_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complete_job',
            old_name='complete_job',
            new_name='complete_update',
        ),
    ]
