# Generated by Django 3.2.4 on 2022-02-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0021_rename_complete_job_complete_job_complete_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='complete_job',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
