# Generated by Django 3.2.4 on 2022-02-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0024_auto_20220218_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complete_job',
            name='cost_com',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
