# Generated by Django 3.2.4 on 2022-02-28 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Jobs', '0025_alter_complete_job_cost_com'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_rebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_r', models.CharField(blank=True, max_length=250, null=True)),
                ('rebooked_on', models.DateTimeField(blank=True, null=True)),
                ('eta_r', models.DateTimeField(blank=True, null=True)),
                ('description_r', models.TextField(blank=True, null=True)),
                ('imei_r', models.CharField(blank=True, max_length=250, null=True)),
                ('fault_r', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fault_r', to='Jobs.fault')),
                ('j_rebook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Jobs.jobs')),
                ('rebooked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
