# Generated by Django 3.2.4 on 2022-02-28 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0026_job_rebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_job_status', to='Jobs.job_status'),
        ),
    ]
