# Generated by Django 3.2.4 on 2022-02-28 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0027_alter_jobs_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='accessories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_acessories', to='Jobs.accessories'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='collection_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='fault',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_faults', to='Jobs.fault'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='imei',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='make',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_make', to='Jobs.make'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_model', to='Jobs.model'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_network', to='Jobs.network'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='passcode',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('PAID', 'PAID'), ('UNPAID', 'UNPAID'), ('CREDIT NOTE', 'CREDIT NOTE'), ('REFUND', 'REFUND')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='sale_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_acessories', to='Jobs.sale_item'),
        ),
    ]
