# Generated by Django 3.2.4 on 2022-02-28 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0028_auto_20220228_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_rebook',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_device', to='Jobs.devices'),
        ),
        migrations.AddField(
            model_name='job_rebook',
            name='make',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_make', to='Jobs.make'),
        ),
        migrations.AddField(
            model_name='job_rebook',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_model', to='Jobs.model'),
        ),
    ]
