# Generated by Django 3.2.4 on 2022-02-28 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0029_auto_20220228_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_rebook',
            name='device',
        ),
        migrations.RemoveField(
            model_name='job_rebook',
            name='make',
        ),
        migrations.RemoveField(
            model_name='job_rebook',
            name='model',
        ),
    ]
