# Generated by Django 3.2.4 on 2022-03-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0030_auto_20220228_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
