# Generated by Django 3.2.4 on 2022-03-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0031_jobs_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
