# Generated by Django 3.2.4 on 2022-03-01 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0034_remove_delivered_customer_deliver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivered',
            name='accessories_deliver',
        ),
        migrations.RemoveField(
            model_name='delivered',
            name='collection_time_deliver',
        ),
        migrations.RemoveField(
            model_name='delivered',
            name='network_deliver',
        ),
        migrations.RemoveField(
            model_name='delivered',
            name='sale_item_deliver',
        ),
    ]
