# Generated by Django 3.2.4 on 2022-03-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0036_auto_20220301_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivered',
            name='delivered',
        ),
        migrations.AddField(
            model_name='jobs',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
