# Generated by Django 3.2.4 on 2022-03-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0041_auto_20220307_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='comments',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
