# Generated by Django 3.2.4 on 2022-03-07 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0042_pictures_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pictures',
            old_name='time',
            new_name='captured_at',
        ),
        migrations.RenameField(
            model_name='pictures',
            old_name='user',
            new_name='captured_by',
        ),
    ]
