# Generated by Django 3.2.4 on 2022-03-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0043_auto_20220307_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='Total_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='vat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
