# Generated by Django 3.2.13 on 2022-06-18 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0044_auto_20220314_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='customer',
        ),
    ]
