# Generated by Django 3.2.4 on 2022-01-30 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory_Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devices', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory_Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=250)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='make_device', to='Inventories.inventory_devices')),
            ],
        ),
        migrations.CreateModel(
            name='Part_colour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Part_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=250)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventories.inventory_make')),
            ],
        ),
    ]
