# Generated by Django 3.2.4 on 2022-01-30 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part_name',
            old_name='part',
            new_name='part_name',
        ),
        migrations.CreateModel(
            name='Inventories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('Part_colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_Part_colour', to='Inventories.part_colour')),
                ('devices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_device', to='Inventories.inventory_devices')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_make', to='Inventories.inventory_make')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_model', to='Inventories.inventory_model')),
                ('part_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_part_name', to='Inventories.part_name')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_supplier', to='Inventories.supplier')),
            ],
        ),
    ]
