# Generated by Django 3.2.4 on 2022-02-13 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventories', '0002_auto_20220130_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory_make',
            name='device',
        ),
        migrations.RemoveField(
            model_name='inventory_model',
            name='make',
        ),
        migrations.DeleteModel(
            name='Inventories',
        ),
        migrations.DeleteModel(
            name='Inventory_Devices',
        ),
        migrations.DeleteModel(
            name='Inventory_Make',
        ),
        migrations.DeleteModel(
            name='Inventory_Model',
        ),
        migrations.DeleteModel(
            name='Part_colour',
        ),
        migrations.DeleteModel(
            name='Part_name',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
