# Generated by Django 3.2.4 on 2022-03-05 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Jobs', '0040_pictures'),
        ('Inventories', '0003_auto_20220213_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part_colour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Part_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Inventories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('devices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_device', to='Jobs.devices')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_make', to='Jobs.make')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_model', to='Jobs.model')),
                ('part_colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_Part_colour', to='Inventories.part_colour')),
                ('part_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_part_name', to='Inventories.part_name')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_supplier', to='Inventories.supplier')),
            ],
        ),
    ]
