# Generated by Django 3.2.4 on 2022-03-07 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Inventories', '0004_inventories_part_colour_part_name_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventories',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventories',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
