# Generated by Django 3.2.4 on 2022-03-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventories', '0006_inventories_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventories',
            name='alocated',
            field=models.BooleanField(default=False),
        ),
    ]
