# Generated by Django 3.2.4 on 2022-03-23 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0044_auto_20220314_1900'),
        ('Inventories', '0007_inventories_alocated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_status', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='inventories',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_inventory', to='Jobs.jobs'),
        ),
        migrations.AddField(
            model_name='inventories',
            name='part_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='i_part_status', to='Inventories.part_status'),
        ),
    ]
