# Generated by Django 3.2.4 on 2022-03-23 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventories', '0008_auto_20220323_1846'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Part_status',
            new_name='Part_status1',
        ),
    ]
