# Generated by Django 3.2.4 on 2022-03-24 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0044_auto_20220314_1900'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Inventories', '0009_rename_part_status_part_status1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('barcode', models.ImageField(blank=True, upload_to='barcodes/')),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('devices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_device', to='Jobs.devices')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_order_part', to='Jobs.jobs')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_make', to='Jobs.make')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_model', to='Jobs.model')),
                ('part_colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_Part_colour', to='Inventories.part_colour')),
                ('part_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_part_name', to='Inventories.part_name')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_supplier', to='Inventories.supplier')),
            ],
        ),
    ]
