# Generated by Django 3.2.4 on 2022-03-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventories', '0010_order_parts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_parts',
            old_name='cost',
            new_name='buying_cost',
        ),
        migrations.RemoveField(
            model_name='order_parts',
            name='barcode',
        ),
        migrations.AddField(
            model_name='order_parts',
            name='part_description',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
