# Generated by Django 3.2.4 on 2022-04-01 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventories', '0011_auto_20220324_0048'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Part_status1',
            new_name='Part_status',
        ),
        migrations.AddField(
            model_name='order_parts',
            name='part_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_part_status', to='Inventories.part_status'),
        ),
    ]
