# Generated by Django 3.2.13 on 2022-05-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventories', '0012_auto_20220401_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventories',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
