# Generated by Django 3.2.13 on 2022-05-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventories', '0015_ordered_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered_parts',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordered_parts',
            name='eta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
