# Generated by Django 3.2.13 on 2022-05-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventories', '0017_alter_ordered_parts_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordered_parts',
            name='buying_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
