# Generated by Django 3.2.13 on 2022-05-21 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventories', '0018_alter_ordered_parts_buying_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordered_parts',
            name='buying_cost',
        ),
        migrations.RemoveField(
            model_name='ordered_parts',
            name='devices',
        ),
        migrations.RemoveField(
            model_name='ordered_parts',
            name='make',
        ),
        migrations.RemoveField(
            model_name='ordered_parts',
            name='model',
        ),
        migrations.RemoveField(
            model_name='ordered_parts',
            name='part_colour',
        ),
        migrations.RemoveField(
            model_name='ordered_parts',
            name='part_description',
        ),
        migrations.RemoveField(
            model_name='ordered_parts',
            name='part_name',
        ),
        migrations.RemoveField(
            model_name='ordered_parts',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='ordered_parts',
            name='supplier',
        ),
    ]
