# Generated by Django 3.2.13 on 2022-05-21 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventories', '0020_ordered_parts_requested_parts_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordered_parts',
            name='job',
        ),
    ]
