# Generated by Django 3.2.4 on 2022-01-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('phone', models.IntegerField()),
                ('landline', models.IntegerField()),
                ('email', models.EmailField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('postcode', models.CharField(max_length=250)),
            ],
        ),
    ]
