# Generated by Django 3.2.4 on 2022-01-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_rename_date_customer_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
