# Generated by Django 3.2.4 on 2022-03-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_customer_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='client_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='vat',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
