# Generated by Django 3.2.13 on 2022-07-14 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_staff_times'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff_times',
        ),
    ]
