# Generated by Django 3.2.13 on 2022-07-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_auto_20220714_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_salary_package',
            name='hour_calculation_wages',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
