# Generated by Django 3.2.13 on 2022-07-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_staff_salary_package_hour_calculation_wages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_salary_package',
            name='hour_calculation_wages',
        ),
        migrations.AddField(
            model_name='staff_times',
            name='hours_worked_field',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
