# Generated by Django 3.2.13 on 2022-07-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_auto_20220716_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_times',
            name='hours_worked_field',
            field=models.DateTimeField(blank=True, max_length=250, null=True),
        ),
    ]
