# Generated by Django 3.2.13 on 2022-07-16 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_alter_staff_times_hours_worked_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_salary_package',
            name='staff_hours_worked',
        ),
        migrations.RemoveField(
            model_name='staff_times',
            name='hours_worked_field',
        ),
        migrations.AddField(
            model_name='staff_times',
            name='d_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff_times',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.staff_salary_package'),
        ),
        migrations.AlterField(
            model_name='staff_times',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff_times',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
