# Generated by Django 3.2.13 on 2022-07-16 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_auto_20220716_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_salary_package',
            name='created_name',
        ),
        migrations.RemoveField(
            model_name='staff_times',
            name='created_by',
        ),
    ]
