# Generated by Django 3.2.13 on 2022-07-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_auto_20220716_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_times',
            name='hours_worked_field',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
