# Generated by Django 3.2.13 on 2022-07-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_alter_staff_times_hours_worked_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_times',
            name='hourly_wages',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
