# Generated by Django 3.2.13 on 2022-07-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0013_staff_times_hourly_wages'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=250, null=True)),
                ('last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('home_number', models.CharField(blank=True, max_length=250, null=True)),
                ('mobile', models.CharField(blank=True, max_length=250, null=True)),
                ('nationility', models.CharField(blank=True, max_length=250, null=True)),
                ('passport_no', models.CharField(blank=True, max_length=250, null=True)),
                ('adress', models.CharField(blank=True, max_length=250, null=True)),
                ('postcode', models.CharField(blank=True, max_length=250, null=True)),
                ('bank_details', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
