# Generated by Django 3.2.4 on 2022-02-22 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Jobs', '0025_alter_complete_job_cost_com'),
        ('Retail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_cart',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer_cart',
            name='reciept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Jobs.reciepts'),
        ),
        migrations.AddField(
            model_name='customer_cart',
            name='sale_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
