# Generated by Django 3.2.4 on 2022-02-22 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Retail', '0003_daily_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_sale',
            name='payment_reciept',
        ),
    ]
