# Generated by Django 3.2.4 on 2022-03-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Retail', '0004_remove_daily_sale_payment_reciept'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_cart',
            name='delivery_comments',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
