# Generated by Django 3.2.4 on 2022-03-15 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0044_auto_20220314_1900'),
        ('Retail', '0005_customer_cart_delivery_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_sale',
            name='d_sale',
        ),
        migrations.AddField(
            model_name='daily_sale',
            name='cost_deliver',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daily_sale',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daily_sale',
            name='delivery_comments',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='daily_sale',
            name='description_deliver',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daily_sale',
            name='device_deliver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_daily_sale', to='Jobs.devices'),
        ),
        migrations.AddField(
            model_name='daily_sale',
            name='fault_deliver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fault_daily_sale', to='Jobs.fault'),
        ),
        migrations.AddField(
            model_name='daily_sale',
            name='imei_deliver',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='daily_sale',
            name='job_deliver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_daily_sale', to='Jobs.jobs'),
        ),
        migrations.AddField(
            model_name='daily_sale',
            name='job_status_deliver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_status_daily_sale', to='Jobs.job_status'),
        ),
        migrations.AddField(
            model_name='daily_sale',
            name='make_deliver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='make_daily_sale', to='Jobs.make'),
        ),
        migrations.AddField(
            model_name='daily_sale',
            name='model_deliver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_daily_sale', to='Jobs.model'),
        ),
        migrations.AddField(
            model_name='daily_sale',
            name='passcode_deliver',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='daily_sale',
            name='payment_status_deliver',
            field=models.CharField(blank=True, choices=[('PAID', 'PAID'), ('UNPAID', 'UNPAID'), ('CREDIT NOTE', 'CREDIT NOTE'), ('REFUND', 'REFUND')], max_length=250, null=True),
        ),
    ]
