# Generated by Django 3.2.4 on 2022-03-18 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Retail', '0006_auto_20220315_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_sale',
            name='payment_type_daily_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_type_daily', to='Retail.payment_type'),
        ),
    ]
