# Generated by Django 3.2.4 on 2022-03-18 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0044_auto_20220314_1900'),
        ('Retail', '0007_daily_sale_payment_type_daily_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_sale',
            name='reciept_daily_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciept_daily_sale', to='Jobs.reciepts'),
        ),
    ]
