# Generated by Django 3.2.13 on 2022-04-11 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accessories', '0004_auto_20220407_1557'),
        ('Retail', '0008_daily_sale_reciept_daily_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acce_Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accessories.retail_accessories')),
            ],
        ),
    ]
