# Generated by Django 3.2.13 on 2022-05-27 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Retail', '0010_sold_acc'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold_acc',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Retail.payment_type'),
        ),
    ]
