# Generated by Django 3.2.13 on 2022-05-27 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accessories', '0006_delete_sold_acc'),
        ('Retail', '0011_sold_acc_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sold_acc',
            name='retail_acc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accessories.retail_accessories'),
        ),
    ]
