# Generated by Django 3.2.13 on 2022-05-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Retail', '0012_sold_acc_retail_acc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sold_acc',
            name='retail_price',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
