# Generated by Django 3.2.13 on 2022-06-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Retail', '0013_alter_sold_acc_retail_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_admin_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
