# Generated by Django 3.2.13 on 2022-07-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Retail', '0016_alter_daily_totals_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_totals',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
