# Generated by Django 3.2.4 on 2022-04-06 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Jobs', '0044_auto_20220314_1900'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceesories_colour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Acceesories_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acce_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Acceesories_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acce_status', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Retail_Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('acce_colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceessories_colour', to='Accessories.acceesories_colour')),
                ('acce_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceessories_part_name', to='Accessories.acceesories_name')),
                ('acce_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accessories_status', to='Accessories.acceesories_status')),
                ('devices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceessories_device', to='Jobs.devices')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceessories_make', to='Jobs.make')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceessories_model', to='Jobs.model')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories_supplier', to='Accessories.supplier')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
