# Generated by Django 3.2.4 on 2022-04-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accessories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retail_accessories',
            name='retail_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
