# Generated by Django 3.2.4 on 2022-04-07 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventories', '0012_auto_20220401_1820'),
        ('Accessories', '0002_retail_accessories_retail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retail_accessories',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories_supplier', to='Inventories.supplier'),
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
