# Generated by Django 3.2.4 on 2022-04-07 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventories', '0012_auto_20220401_1820'),
        ('Accessories', '0003_auto_20220407_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retail_accessories',
            name='acce_colour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceessories_colour', to='Inventories.part_colour'),
        ),
        migrations.DeleteModel(
            name='Acceesories_colour',
        ),
    ]
