# Generated by Django 3.2.13 on 2022-05-23 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0044_auto_20220314_1900'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accessories', '0004_auto_20220407_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sold_acc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retail_price', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('acce_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_acceessories_part_name', to='Accessories.acceesories_name')),
                ('devices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_acceessories_device', to='Jobs.devices')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_acceessories_make', to='Jobs.make')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_acceessories_model', to='Jobs.model')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
