# Generated by Django 3.2.13 on 2022-05-23 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accessories', '0005_sold_acc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sold_acc',
        ),
    ]
