# Generated by Django 3.2.13 on 2022-07-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accessories', '0006_delete_sold_acc'),
    ]

    operations = [
        migrations.AddField(
            model_name='retail_accessories',
            name='alocated',
            field=models.BooleanField(default=False),
        ),
    ]
